// angular-frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { SelectTextfieldComponent } from '../components/select-textfield/select-textfield.component';
import { TextfieldsComponent } from '../components/textfields/textfields.component'; 

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, TextfieldsComponent,SelectTextfieldComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'e-HealthHub';
  // textValue: string = '';
  // password: string = '';

  // selectedOption: any = undefined;
  // selectOptions: { value: any, label: string }[];

  // constructor() {
  //   // Sample options data
  //   this.selectOptions = [
  //     { value: 'option1', label: 'Option 1' },
  //     { value: 'option2', label: 'Option 2' },
  //     { value: 'option3', label: 'Option 3' }
  //   ];
  // }
}

<!-- <app-textfields
  type="text"
  size="lg"
  placeholder="Enter Text"
  [(value)]="textValue"
></app-textfields>
<br />
<app-textfields
  type="password"
  size="md"
  placeholder="Enter Password"
  [(value)]="password"
></app-textfields>
<br /><br /><br />
<div>
  <app-select-textfield
    [value]="selectedOption"
    [placeholder]="'Select an option'"
    [options]="selectOptions"
  ></app-select-textfield>
</div> -->

<router-outlet></router-outlet>

// vue-frontend/src/App.vue
<template>
  <div id="app">
    <!-- <TextField placeholder="Small TextField" size="small" v-model="smallTextValue" /><br/>
    <TextField placeholder="Medium TextField" size="medium" v-model="mediumTextValue" /><br/>
    <TextField placeholder="Large TextField" size="large" v-model="largeTextValue" /> -->
    <!-- <PasswordInput placeholder="Enter Password" v-model="password" /> -->
    <!-- <SelectTextField :options="options" v-model="selectedOption" placeholder="Select an option" /> -->
    <DoctorRegister />
  </div>
</template>

<script>
import TextField from "./components/TextFields.vue";
import PasswordInput from "./components/PasswordTextField.vue";
import SelectTextField from "./components/SelectTextField.vue";
import DoctorRegister from "./Pages/DoctorRegister.vue";

export default {
  name: "App",
  components: {
    TextField,
    PasswordInput,
    SelectTextField,
    DoctorRegister,
  },
  data() {
    return {
      smallTextValue: "",
      mediumTextValue: "",
      largeTextValue: "",
      password: "",
      selectedOption: "",
      options: [
        { value: "option1", label: "Option 1" },
        { value: "option2", label: "Option 2" },
        { value: "option3", label: "Option 3" },
      ],
    };
  },
};
</script>

<style>
#app {
  font-family: Arial, sans-serif;
  text-align: center;
  margin-top: 20px;
}
</style>
