// angular-frontend/src/app/pages/dashboard/dashboard.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.css'
})

export class DashboardComponent {
userimg : string = '../assets/user.png';
chart : string = '../assets/chart.png';

currentMonth: string= '';
  daysInMonth: number[] = [];

  constructor(private router: Router) {
    this.updateCurrentMonth();
  }

  previous() {
    this.updateMonth(-1);
  }

  next() {
    this.updateMonth(1);
  }

  updateMonth(monthsToAdd: number) {
    const newMonth = new Date(this.currentMonth);
    newMonth.setMonth(newMonth.getMonth() + monthsToAdd);
    this.currentMonth = newMonth.toLocaleString('default', { month: 'long', year: 'numeric' });
    this.daysInMonth = this.getDaysInMonth(newMonth.getMonth(), newMonth.getFullYear());
  }

  updateCurrentMonth() {
    const date = new Date();
    this.currentMonth = date.toLocaleString('default', { month: 'long', year: 'numeric' });
    this.daysInMonth = this.getDaysInMonth(date.getMonth(), date.getFullYear());
  }

  getDaysInMonth(month: number, year: number): number[] {
    const date = new Date(year, month, 1);
    const days: number[] = [];
    while (date.getMonth() === month) {
      days.push(date.getDate());
      date.setDate(date.getDate() + 1);
    }
    return days;
  }

  navigateToPatientList() {
    this.router.navigate(['/']);
  }

  data = [
    {
      name: "John Doe",
      currentDisease: "Fever",
      nextAppointmentDate: "2024-02-10",
    },
    {
      name: "Jane Smith",
      currentDisease: "Cough",
      nextAppointmentDate: "2024-02-15",
    },
    {
      name: "Alice Johnson",
      currentDisease: "Headache",
      nextAppointmentDate: "2024-02-18",
    },
    {
      name: "Bob Williams",
      currentDisease: "Back Pain",
      nextAppointmentDate: "2024-02-22",
    },
    {
      name: "Eva Davis",
      currentDisease: "Allergies",
      nextAppointmentDate: "2024-02-28",
    },
  ];
}



<div class="dashboard-container">
  <div class="dashboard-container-one">
    <div>
      <h1>Good morning, Dr. xxxxx</h1>
      <p>
        You have 7 patients remaining today! <br />
        Remember to record your details today.
      </p>
    </div>
    <div class="dashboard-user-image">
      <img [src]="userimg" alt="" />
    </div>
  </div>

  <div class="dashboard-container-two">
    <img [src]="chart" alt="Chart" />
    <div class="calendar-container">
      <div class="header">
        <button (click)="previous()">Previous</button>
        <span>{{ currentMonth }}</span>
        <button (click)="next()">Next</button>
      </div>
      <div class="days-header">
        <div class="day">Mon</div>
        <div class="day">Tue</div>
        <div class="day">Wed</div>
        <div class="day">Thu</div>
        <div class="day">Fri</div>
        <div class="day">Sat</div>
        <div class="day">Sun</div>
      </div>
      <div class="days">
        <div class="day" *ngFor="let day of daysInMonth">
          {{ day }}
        </div>
      </div>
    </div>
  </div>

  <div class="dashboard-container-three">
    <div class="dashboard-header">
      <h2>Recent Patient List</h2>
      <a (click)="navigateToPatientList()">View All</a>
    </div>
    <div class="patient-table-container">
      <table class="patient-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Current Disease</th>
            <th>Next Appointment Date</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let row of data">
            <td>{{ row.name }}</td>
            <td>{{ row.currentDisease }}</td>
            <td>{{ row.nextAppointmentDate }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

// react-frontend/src/Pages/Dashboard.js
import React from "react";
import "./Dashboard.css";
import Calendar from "react-calendar";
import userimg from "../assets/user.png";
import chart from "../assets/chart.png";
import { useState } from "react";
import { Link } from "react-router-dom";

function Dashboard() {
  const [date, setDate] = useState(new Date());

  const handleDateChange = (newDate) => {
    setDate(newDate);
  };

  const data = [
    {
      name: "John Doe",
      currentDisease: "Fever",
      nextAppointmentDate: "2024-02-10",
    },
    {
      name: "Jane Smith",
      currentDisease: "Cough",
      nextAppointmentDate: "2024-02-15",
    },
    {
      name: "Alice Johnson",
      currentDisease: "Headache",
      nextAppointmentDate: "2024-02-18",
    },
    {
      name: "Bob Williams",
      currentDisease: "Back Pain",
      nextAppointmentDate: "2024-02-22",
    },
    {
      name: "Eva Davis",
      currentDisease: "Allergies",
      nextAppointmentDate: "2024-02-28",
    },
  ];

  return (
    <div className="dashboard-container">
      <div className="dashboard-container-one">
        <div>
          <h1>Good morning, Dr. xxxxx</h1>
          <p>
            You have 7 patients remaining today! <br /> Remember to record your
            details today.
          </p>
        </div>
        <div className="dashboard-user-image">
          <img src={userimg} alt="User" />
        </div>
      </div>

      <div className="dashboard-container-two">
        <img src={chart} alt="Chart" />
        <div className="calendar-container">
          <Calendar onChange={handleDateChange} value={date} />
        </div>
      </div>

      <div className="dashboard-container-three">
        <div className="dashboard-header">
          <h2>Recent Patient List</h2>
          <Link to="/patient-list">View All</Link>
        </div>
        <div className="patient-table-container">
          <table className="patient-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Current Disease</th>
                <th>Next Appointment Date</th>
              </tr>
            </thead>
            <tbody>
              {data.map((row, index) => (
                <tr key={index}>
                  <td>{row.name}</td>
                  <td>{row.currentDisease}</td>
                  <td>{row.nextAppointmentDate}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

export default Dashboard;
