// angular-frontend/src/app/pages/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, NavigationEnd, RouterModule } from '@angular/router';
import { faHouseChimney, faUser, faClipboardList, faList } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterModule,FontAwesomeModule, CommonModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent implements OnInit {
  userimg : string = '../assets/user.png';
  isNavVisible: boolean = false;
  activeLink: string = "";
  faHouseChimney= faHouseChimney;
  faUser = faUser;
  faClipboardList = faClipboardList;
  faList = faList;

  constructor(private router: Router) {}

   navigateToPatientList(){
    this.router.navigate(['/patient-list'])
  }

  navigateToPatientRegister() {
    this.router.navigate(['/patient-register']);
  }

  navigateToDashboard() {
    this.router.navigate(['/dashboard']);
  }

   navigateToDoctorProfile(){
    this.router.navigate(['/doctor-profile'])
  }

ngOnInit(): void {
    this.setActiveLink();
    this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.setActiveLink();
      }
    });
  }

   setActiveLink(): void {
    this.activeLink = this.router.url;
  }

  toggleNavVisibility() {
    this.isNavVisible = !this.isNavVisible;
  }

  closeNav() {
    this.isNavVisible = false;
  }

}

<div class="navbar-container">
  <button class="toggle-nav-btn" (click)="toggleNavVisibility()">
    &#9776;
  </button>
  <div
    class="overlay"
    [class.visible]="isNavVisible"
    (click)="closeNav()"
  ></div>

  <div class="navbar-container-one" [class.visible]="isNavVisible">
    <img class="nav-image" [src]="userimg" alt="" />
    <h3 class="doctor-details">Dr: xxxxxx</h3>
    <h3 class="doctor-details">ID: 12345678</h3>
  </div>

  <div class="navbar-container-two" [class.visible]="isNavVisible">
    <a
      (click)="navigateToDashboard()"
      class="nav-link"
      [class.active-link]="activeLink === '/dashboard'"
      (click)="closeNav()"
    >
      <div class="icon-text-container">
        <fa-icon [icon]="faHouseChimney"></fa-icon>
        <span>Dashboard</span>
      </div>
    </a>

    <a
      (click)="navigateToDoctorProfile()"
      class="nav-link"
      [class.active-link]="activeLink === '/doctor-profile'"
      (click)="closeNav()"
    >
      <div class="icon-text-container">
        <fa-icon [icon]="faUser"></fa-icon>
        My Profile
      </div>
    </a>

    <a
      (click)="navigateToPatientRegister()"
      class="nav-link"
      [class.active-link]="activeLink.includes('/patient-register')"
      (click)="closeNav()"
    >
      <div class="icon-text-container">
        <fa-icon [icon]="faClipboardList"></fa-icon>
        Patient Registration
      </div>
    </a>

    <a
      (click)="navigateToPatientList()"
      class="nav-link"
      [class.active-link]="activeLink === '/patient-list'"
      (click)="closeNav()"
    >
      <div class="icon-text-container">
        <fa-icon [icon]="faList"></fa-icon>
        Patient List
      </div>
    </a>
  </div>
</div>

// react-frontend/src/Pages/Navbar.js
import React, { useState, useEffect } from "react";
import "./Navbar.css";
import { FaHome, FaUser, FaClipboardList, FaList } from "react-icons/fa";
import { NavLink, useLocation } from "react-router-dom";
import userimg from "../assets/user.png";

function Navbar() {
  const [isNavVisible, setIsNavVisible] = useState(false);

  const toggleNavVisibility = () => {
    setIsNavVisible(!isNavVisible);
  };

  const closeNav = () => {
    setIsNavVisible(false);
  };

  const location = useLocation();
  const [activeLink, setActiveLink] = useState("");

  useEffect(() => {
    setActiveLink(location.pathname);
  }, [location]);

  return (
    <div className="navbar-container">
      <button className="toggle-nav-btn" onClick={toggleNavVisibility}>
        &#9776;
      </button>
      <div
        className={`overlay ${isNavVisible ? "visible" : ""}`}
        onClick={closeNav}
      ></div>

      <div className={`navbar-container-one ${isNavVisible ? "visible" : ""}`}>
        <img className="nav-image" src={userimg} alt="" />
        <h3 className="doctor-details">Dr: xxxxxx</h3>
        <h3 className="doctor-details">ID: 12345678</h3>
      </div>

      <div className={`navbar-container-two ${isNavVisible ? "visible" : ""}`}>
        <NavLink
          to="/dashboard"
          className={`nav-link ${
            activeLink === "/dashboard" ? "active-link" : ""
          }`}
          onClick={closeNav}
        >
          <FaHome />
          Dashboard
        </NavLink>
        <NavLink
          to="/doctor-profile"
          className={`nav-link ${
            activeLink === "/doctor-profile" ? "active-link" : ""
          }`}
          onClick={closeNav}
        >
          <FaUser />
          My Profile
        </NavLink>
        <NavLink
          to="/patient-register"
          className={`nav-link ${
            activeLink === "/patient-register" ? "active-link" : ""
          }`}
          onClick={closeNav}
        >
          <FaClipboardList />
          Patient Registration
        </NavLink>
        <NavLink
          to="/patient-list"
          className={`nav-link ${
            activeLink === "/patient-list" ? "active-link" : ""
          }`}
          onClick={closeNav}
        >
          <FaList />
          Patient List
        </NavLink>
      </div>
    </div>
  );
}

export default Navbar;
