// angular-frontend/src/app/pages/patient-list/patient-list.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faSearch} from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-patient-list',
  standalone: true,
  imports: [CommonModule,FontAwesomeModule],
  templateUrl: './patient-list.component.html',
  styleUrl: './patient-list.component.css'
})
export class PatientListComponent {
  faSearch =faSearch;
  searchQuery: string = '';

  onSearchInput(value: string) {
    this.searchQuery = value;
    // You can add additional logic here, such as triggering search functionality
  }

   data = [
    {
      name: "John Doe",
      age: 45,
      currentDisease: "Fever",
      mobileNumber: 123456789,
      nextAppointmentDate: "2024-02-10",
    },
    {
      name: "Jane Smith",
      age: 25,
      currentDisease: "Cough",
      mobileNumber: 123456789,
      nextAppointmentDate: "2024-02-15",
    },
    {
      name: "Alice Johnson",
      age: 40,
      currentDisease: "Headache",
      mobileNumber: 123456789,
      nextAppointmentDate: "2024-02-18",
    },
    {
      name: "Bob Williams",
      age: 32,
      currentDisease: "Back Pain",
      mobileNumber: 123456789,
      nextAppointmentDate: "2024-02-22",
    },
    {
      name: "Eva Davis",
      age: 60,
      currentDisease: "Allergies",
      mobileNumber: 123456789,
      nextAppointmentDate: "2024-02-28",
    },
     {
      name: "",
      age: '',
      currentDisease: "",
      mobileNumber: '',
      nextAppointmentDate: "",
    }
  ];

  constructor(private router: Router) {}

  redirectToPatientProfile() {
    this.router.navigate(['/patient-profile']); 
  }
}

<div class="list-container">
  <h1>Patient List</h1>
  <div class="list-container-one">
    <div class="search-bar">
      <input type="text" placeholder="Search..." [value]="searchQuery" />
      <fa-icon class="search-icon" [icon]="faSearch"></fa-icon>
    </div>
  </div>

  <div class="list-container-two">
    <div class="patient-table-container">
      <table class="patient-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Current Disease</th>
            <th>Mobile Number</th>
            <th>Next Appointment Date</th>
          </tr>
        </thead>
        <tbody>
          <tr
            *ngFor="let row of data; let i = index"
            (click)="redirectToPatientProfile()"
          >
            <td>{{ row.name }}</td>
            <td>{{ row.age }}</td>
            <td>{{ row.currentDisease }}</td>
            <td>+94 {{ row.mobileNumber }}</td>
            <td>{{ row.nextAppointmentDate }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

// react-frontend/src/Pages/PatientList.js
import React from "react";
import "./PatientList.css";
import { FaSearch } from "react-icons/fa";
import { useNavigate } from "react-router-dom";

function PatientList() {
  const navigate = useNavigate();

  const data = [
    {
      name: "John Doe",
      age: 45,
      currentDisease: "Fever",
      mobileNumber: 123456789,
      nextAppointmentDate: "2024-02-10",
    },
    {
      name: "Jane Smith",
      age: 25,
      currentDisease: "Cough",
      mobileNumber: 123456789,
      nextAppointmentDate: "2024-02-15",
    },
    {
      name: "Alice Johnson",
      age: 40,
      currentDisease: "Headache",
      mobileNumber: 123456789,
      nextAppointmentDate: "2024-02-18",
    },
    {
      name: "Bob Williams",
      age: 32,
      currentDisease: "Back Pain",
      mobileNumber: 123456789,
      nextAppointmentDate: "2024-02-22",
    },
    {
      name: "Eva Davis",
      age: 60,
      currentDisease: "Allergies",
      mobileNumber: 123456789,
      nextAppointmentDate: "2024-02-28",
    },

    {
      name: "",
      age: "",
      currentDisease: "",
      mobileNumber: "",
      nextAppointmentDate: "",
    },
    {
      name: "",
      age: "",
      currentDisease: "",
      mobileNumber: "",
      nextAppointmentDate: "",
    },
  ];

  const redirectToPatientProfile = () => {
    navigate("/patient-profile");
  };

  return (
    <div className="list-container">
      <h1>Patient List</h1>
      <div className="list-container-one">
        <div className="search-bar">
          <input type="text" placeholder="Search..." />
          <FaSearch className="search-icon" />
        </div>
      </div>

      <div className="list-container-two">
        <div className="patient-table-container">
          <table className="patient-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Current Disease</th>
                <th>Mobile Number</th>
                <th>Next Appointment Date</th>
              </tr>
            </thead>
            <tbody>
              {data.map((row, index) => (
                <tr key={index} onClick={redirectToPatientProfile}>
                  <td>{row.name}</td>
                  <td>{row.age}</td>
                  <td>{row.currentDisease}</td>
                  <td>+94 {row.mobileNumber}</td>
                  <td>{row.nextAppointmentDate}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

export default PatientList;
