// react-frontend/src/Pages/DoctorSignin.js
import { Link } from "react-router-dom";
import img2 from "../assets/image2.png";
import logo from "../assets/logo.png";
import { LargeTextField, PasswordInput } from "../Components/Textfeilds";
import "./DoctorSignin.css";

function DoctorSignin() {
  return (
    <div className="signin-container">
      <div className="signin-container-one">
        {/* <img style={{ width: "500px", height: "500px" }} src={logo} alt="" /> */}
        <div className="welcome-meassage">
          <h1>Hi,</h1>
          <h1>Welcome Back</h1>
        </div>

        <img src={img2} alt="" />
      </div>

      <div className="signin-container-two">
        <div className="signin-header-link">
          <h3 className="create-account-heading">Create an account?</h3>
          <Link className="create-account-heading" to="/doctor-register">
            Sign up
          </Link>
        </div>

        <div className="signin-body">
          <div className="signin-header">
            <h1>Login {""} </h1> <h1>to eHealthHub</h1>
          </div>

          <div className="signin-textfield-container">
            <LargeTextField placeholder={"Enter your Email"} />
            <PasswordInput placeholder={"Enter your password"} />
            <Link to="#" style={{ color: "white" }}>
              Forgot Password?
            </Link>
          </div>
          <div className="Signin-button-section">
            <button className="signin-button">
              <h2>Sign in</h2>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default DoctorSignin;

// vue-frontend/src/Pages/DoctorSignin.vue
<template>
  <div class="signin-container">
    <div class="signin-container-one">
      <div class="welcome-meassage">
        <h1>Hi,</h1>
        <h1>Welcome Back</h1>
      </div>
      <img :src="img2" alt="" />
    </div>

    <div class="signin-container-two">
      <div class="signin-header-link">
        <h3 class="create-account-heading">Create an account?</h3>
        <router-link to="/doctor-register"> Sign up </router-link>
      </div>

      <div class="signin-body">
        <div class="signin-header">
          <h1>Login</h1>
          <h1>to eHealthHub</h1>
        </div>

        <div class="signin-textfield-container">
          <TextField
            size="large"
            v-model="largeTextValue"
            placeholder="Enter your Email"
          />
          <PasswordInput v-model="password" placeholder="Enter your password" />
          <router-link to="#"> Forgot Password? </router-link>
        </div>
        <div class="Signin-button-section">
          <button class="signin-button" onClick="{handleSignInClick}">
            <h2>Sign in</h2>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import img2 from "../assets/image2.png";
import TextField from "../components/TextFields.vue";
import PasswordInput from "../components/PasswordTextField.vue";

export default {
  data() {
    return {
      img2: img2,
    };
  },
  components: {
    TextField,
    PasswordInput,
  },
  methods: {
    handleSignInClick() {
      this.$router.push("/");
    },
  },
};
</script>

<style>
.signin-container {
  display: flex;
  flex-direction: row;
  height: 100vh;
  width: 100%;
}

.signin-container-one {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  width: 40%;
}

.welcome-meassage {
  display: flex;
  flex-direction: row;
  font-family: Cambria, Cochin, Georgia, Times, "Times New Roman", serif;
  font-size: x-large;
}

.signin-container-one h1,
.signin-container-one h1 {
  margin: 0;
  margin-right: 10px;
}

.signin-container-two {
  display: flex;
  flex-direction: column;
  height: 100vh;
  width: 60%;
  background-color: var(--primary-color);
}

.signin-header-link {
  display: flex;
  justify-content: flex-end;
  align-items: center;
  padding: 20px;
}

.signin-header-link router-link {
  cursor: pointer;
  color: aliceblue;
  text-decoration: underline;
}

.create-account-heading {
  color: white;
  margin-right: 10px;
}

.signin-body {
  display: flex;
  flex-direction: column;
  height: 100%;
  align-items: center;
  justify-content: center;
}
.signin-header {
  display: flex;
  flex-direction: row;
  font-size: 30px;
  color: white;
  margin-bottom: 40px;
}

.signin-header h1:first-child {
  margin-right: 10px;
}

.signin-textfield-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 15px;
}

.signin-textfield-container router-link {
  color: aliceblue;
  cursor: pointer;
}
.Signin-button-section {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 75px;
}

.signin-button {
  color: var(--primary-color);
  background-color: white;
  padding: 0 50px 0 50px;
  border: 0;
  border-radius: 10px;
  font-size: medium;
}

.signin-button:hover {
  background-color: rgb(185, 182, 182);
}

@media screen and (max-width: 1366px) {
  .signin-container {
    display: flex;
    flex-direction: column;
  }

  .signin-container-one {
    display: none;
  }

  .signin-container-two {
    width: 100%;
  }

  .signin-header {
    font-size: 30px;
  }

  .signin-body {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .signin-button {
    font-size: small;
  }
}

@media screen and (max-width: 768px) {
  .signin-container {
    flex-direction: column;
  }

  .signin-container-one {
    display: none;
  }

  .signin-container-two {
    width: 100%;
  }

  .signin-header {
    font-size: 20px;
  }
  .signin-body {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .signin-button {
    font-size: small;
    padding: auto;
  }
}

@media (max-width: 400px) {
  .signin-header-link h3 {
    font-size: medium;
  }

  .signin-header h1 {
    font-size: larger;
  }

  .signin-button {
    padding: 0 30px 0 30px;
  }

  .signin-button h3 {
    font-size: small;
  }
}
</style>
