// react-frontend/src/Pages/Navbar.js
import React, { useState, useEffect } from "react";
import "./Navbar.css";
import { FaHome, FaUser, FaClipboardList, FaList } from "react-icons/fa";
import { NavLink, useLocation } from "react-router-dom";
import userimg from "../assets/user.png";
import { useAuth } from "./AuthContext";
import { initializeApp } from "firebase/app";
import {
  getFirestore,
  collection,
  query,
  where,
  getDocs,
} from "firebase/firestore";
import { firebaseConfig } from "../firebase-config";

function Navbar() {
  const [isNavVisible, setIsNavVisible] = useState(false);
  const [userData, setUserData] = useState(null);
  const { userUid } = useAuth();
  const location = useLocation();
  const [activeLink, setActiveLink] = useState("");

  const toggleNavVisibility = () => {
    setIsNavVisible(!isNavVisible);
  };

  const closeNav = () => {
    setIsNavVisible(false);
  };

  useEffect(() => {
    const fetchUserData = async () => {
      try {
        if (userUid) {
          const firebaseApp = initializeApp(firebaseConfig);
          const db = getFirestore(firebaseApp);

          const q = query(
            collection(db, "react-doctor-details"),
            where("uid", "==", userUid)
          );
          const querySnapshot = await getDocs(q);

          if (!querySnapshot.empty) {
            const userDoc = querySnapshot.docs[0];
            const userData = userDoc.data();
            console.log("Dashboard User Name:", userData.fullName);
            setUserData(userData);
          } else {
            console.log("User document not found for UID:", userUid);
          }
        }
      } catch (error) {
        console.error("Error fetching user data:", error);
      }
    };

    fetchUserData();
  }, [userUid]); // Run effect whenever userUid changes

  useEffect(() => {
    setActiveLink(location.pathname);
  }, [location]);

  return (
    <div className="navbar-container">
      <button className="toggle-nav-btn" onClick={toggleNavVisibility}>
        &#9776;
      </button>
      <div
        className={`overlay ${isNavVisible ? "visible" : ""}`}
        onClick={closeNav}
      ></div>

      {userData && (
        <div
          className={`navbar-container-one ${isNavVisible ? "visible" : ""}`}
        >
          <img className="nav-image" src={userimg} alt="" />
          <h3 className="doctor-details">Dr: {userData.fullName}</h3>
          <h3 className="doctor-details">ID: {userData.doctorId}</h3>
        </div>
      )}

      <div className={`navbar-container-two ${isNavVisible ? "visible" : ""}`}>
        <NavLink
          to="/dashboard"
          className={`nav-link ${
            activeLink === "/dashboard" ? "active-link" : ""
          }`}
          onClick={closeNav}
        >
          <FaHome />
          Dashboard
        </NavLink>
        <NavLink
          to="/doctor-profile"
          className={`nav-link ${
            activeLink === "/doctor-profile" ? "active-link" : ""
          }`}
          onClick={closeNav}
        >
          <FaUser />
          My Profile
        </NavLink>
        <NavLink
          to="/patient-register"
          className={`nav-link ${
            activeLink === "/patient-register" ? "active-link" : ""
          }`}
          onClick={closeNav}
        >
          <FaClipboardList />
          Patient Registration
        </NavLink>
        <NavLink
          to="/patient-list"
          className={`nav-link ${
            activeLink === "/patient-list" ? "active-link" : ""
          }`}
          onClick={closeNav}
        >
          <FaList />
          Patient List
        </NavLink>
      </div>
    </div>
  );
}

export default Navbar;

// vue-frontend/src/Pages/Navbar.vue
<template>
  <div class="navbar-container">
    <button class="toggle-nav-btn" @click="toggleNavVisibility">&#9776;</button>
    <div
      class="overlay"
      :class="{ visible: isNavVisible }"
      @click="closeNav"
    ></div>

    <div class="navbar-container-one" :class="{ visible: isNavVisible }">
      <img class="nav-image" :src="user" alt="" />
      <h3 class="doctor-details" v-if="userData">Dr: {{ userData.fullName }}</h3>
      <h3 class="doctor-details" v-if="userData">ID: {{ userData.doctorId }}</h3>
    </div>

    <div class="navbar-container-two" :class="{ visible: isNavVisible }">
      <router-link to="/dashboard" class="nav-link" :class="{ 'active-link': isLinkActive('/dashboard') }" @click="closeNav">
        <font-awesome-icon icon="home" />
        Dashboard
      </router-link>
      <router-link to="/doctor-profile" class="nav-link" :class="{ 'active-link': isLinkActive('/doctor-profile') }" @click="closeNav">
        <font-awesome-icon icon="user" />
        My Profile
      </router-link>
      <router-link to="/patient-register" class="nav-link" :class="{ 'active-link': isLinkActive('/patient-register') }" @click="closeNav">
        <font-awesome-icon icon="clipboard-list" />
        Patient Registration
      </router-link>
      <router-link to="/patient-list" class="nav-link" :class="{ 'active-link': isLinkActive('/patient-list') }" @click="closeNav">
        <font-awesome-icon icon="list" />
        Patient List
      </router-link>
    </div>
  </div>
</template>

<script>
import user from "../assets/user.png";
import { ref } from "vue";
import { useRoute } from "vue-router";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
  faHome,
  faUser,
  faClipboardList,
  faList,
} from "@fortawesome/free-solid-svg-icons";
import { library } from "@fortawesome/fontawesome-svg-core";
import { mapGetters } from "vuex";
import { initializeApp } from "firebase/app";
import {
  getFirestore,
  collection,
  query,
  where,
  getDocs,
} from "firebase/firestore";
import { firebaseConfig } from "../firebase";

export default {
  data() {
    return {
      user: user,
      userData: null,
    };
  },
  components: {
    FontAwesomeIcon,
  },
  created() {
    library.add(faHome, faUser, faClipboardList, faList);
  },
  setup() {
    const isNavVisible = ref(false);
    const route = useRoute();

    const toggleNavVisibility = () => {
      isNavVisible.value = !isNavVisible.value;
    };

    const closeNav = () => {
      isNavVisible.value = false;
    };

     const isLinkActive = (path) => {
      return route.path === path;
    };

    return {
      isNavVisible,
      toggleNavVisibility,
      closeNav,
      route,
      isLinkActive
    };
  },

  computed: {
    // Map the 'getUserUid' getter from the Vuex store
    ...mapGetters("auth", ["getUserUid"]),
  },
 methods: {
    async fetchData() {
      try {
        const userUid = this.getUserUid;
        if (userUid) {
          const firebaseApp = initializeApp(firebaseConfig);
          const db = getFirestore(firebaseApp);

          const q = query(
            collection(db, "vue-doctor-details"),
            where("uid", "==", userUid)
          );

          const querySnapshot = await getDocs(q);

          if (!querySnapshot.empty) {
            const userDoc = querySnapshot.docs[0];
            const userData = userDoc.data();
            console.log("Dashboard User Name:", userData.fullName);
            this.userData = userData;
          } else {
            console.log("User document not found for UID:", userUid);
          }
        }
      } catch (error) {
        console.error("Error fetching user data:", error);
      }
    },
  }, mounted() {
    // Fetch data or perform actions upon component mount
    this.fetchData();
  },
};

</script>

<style>
.navbar-container {
  position: fixed;
  top: 0;
  left: 0;
  bottom: 0;
  width: 20vw;
  max-width: 300px;
}

.navbar-container-one {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background-color: var(--primary-color);
  height: 30%;
}

.nav-image {
  height: 100px;
  width: 100px;
}

.doctor-details {
  color: rgb(255, 255, 255);
  margin-bottom: 0;
}

.navbar-container-two {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  background-color: #f5d5ae;
  height: 70%;
  padding: 20px 0 0 50px;
}

.nav-link {
  text-decoration: none;
  color: rgb(35, 35, 35);
  margin: 20px 0;
  display: flex;
  align-items: center;
  font-weight: bold;
  transition: color 0.3s ease-in-out;
  cursor: pointer;
}

.nav-link:hover {
  color: rgb(0, 0, 0);
  transform: scale(1.05);
}

.nav-link span {
  margin-right: 10px;
}

.nav-link svg {
  margin-right: 10px;
}

.nav-link.active-link {
  color: var(--primary-color);
}

.toggle-nav-btn {
  display: none;
}

.overlay {
  display: none;
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  z-index: 1000; /* Set a high z-index to ensure it's above other elements */
}

.overlay.visible {
  display: block;
}

@media screen and (max-width: 1366px) {
  .nav-link {
    padding-left: 10px;
    margin-left: 0;
    /* white-space: nowrap; */
  }
  .navbar-container-one {
    padding: 20px;
  }
  .navbar-container-two {
    padding: 30px;
  }
}

@media screen and (max-width: 768px) {
  .navbar-container {
    display: flex;
    flex-direction: column;
    position: relative;
    width: 0;
  }

  .toggle-nav-btn {
    display: block;
    position: absolute;
    top: 10px;
    left: 10px;
    font-size: 20px;
    cursor: pointer;
    background: none;
    border: none;
    outline: none;
    z-index: 1004;
  }

  .navbar-container-one,
  .navbar-container-two {
    display: none;
    position: fixed;
    width: 100vw;
  }

  .navbar-container-one.visible,
  .navbar-container-two.visible {
    display: flex;
    position: fixed;
    width: 100vw;
    z-index: 1003;
  }

  .navbar-container-one.visible {
    top: 0;
    flex-direction: column;
    align-items: center;
    padding: 20px 0 0 20px;
  }

  .navbar-container-two.visible {
    align-items: flex-start;
    padding: 0 0 0 20px;
    bottom: 0;
  }
}

@media (max-width: 375px) {
  .navbar-container-one.visible {
    height: 25%;
    padding-bottom: 20px;
  }
}
</style>
