// react-frontend/src/Pages/DoctorRegister.js
import img1 from "../assets/image1.png";
import { LargeTextField, PasswordInput } from "../Components/Textfeilds";
import { useState } from "react";
import "./DoctorRegister.css";
import { Link } from "react-router-dom";

function DoctorRegister() {
  const [profilePic, setProfilePic] = useState(null);

  const handleFileChange = (event) => {
    const file = event.target.files[0];

    if (file) {
      setProfilePic(URL.createObjectURL(file));
    }
  };

  return (
    <div className="container">
      <div className="container-one">
        <img src={img1} alt="" />
      </div>

      <div className="container-two">
        <div className="signup-header">
          <h4 style={{ marginRight: 5 }}>Already have an account?</h4>
          <Link to="/doctor-signin">Sign in</Link>
        </div>

        <div className="header">
          <h1 style={{ color: "var(--primary-color)", fontSize: "50px" }}>
            Doctor Sign Up
          </h1>
        </div>

        <div className="textField-container">
          <div className="textField-container-one">
            <p>Full Name:</p>
            <LargeTextField placeholder={"Enter your name"} />
            <br />
            <p>Doctor Id:</p>
            <LargeTextField placeholder={"Enter your Id"} /> <br />
            <p>Speciality:</p>
            <LargeTextField placeholder={"Enter speciality"} /> <br />
          </div>

          <div className="textField-container-one">
            <p>Email:</p>
            <LargeTextField placeholder={"Enter email address"} /> <br />
            <p>Mobile Number:</p>
            <LargeTextField placeholder={"Enter mobile number"} /> <br />
            <p>Hospital Name:</p>
            <LargeTextField placeholder={"Enter hospital name"} /> <br />
          </div>
        </div>

        <div className="textField-container">
          <div className="textField-container-one">
            <p>Password:</p>
            <PasswordInput placeholder={"Enter password"} />
          </div>

          <div className="textField-container-one">
            <p>Confirm Password:</p>
            <PasswordInput placeholder={"Re-enter password"} />
          </div>
        </div>

        <div className="containers">
          <div className="profile-section">
            {profilePic && (
              <div>
                <div className="profile-pic-container">
                  <img src={profilePic} alt="Profile" className="profile-pic" />
                </div>
              </div>
            )}
            <div>
              <div className="label-container">
                <input
                  type="file"
                  id="fileInput"
                  accept="image/*"
                  onChange={handleFileChange}
                />
                <label htmlFor="fileInput">Choose profile picture</label>
              </div>
            </div>
          </div>

          <div className="button-section">
            <button className="signup-button">
              <h2>Sign Up</h2>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default DoctorRegister;

// angular-frontend/src/app/pages/doctor-register/doctor-register.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { TextfieldsComponent } from '../../../components/textfields/textfields.component';

@Component({
  selector: 'app-doctor-register',
  standalone: true,
  imports: [TextfieldsComponent,CommonModule],
  templateUrl: './doctor-register.component.html',
  styleUrl: './doctor-register.component.css'
})
export class DoctorRegisterComponent {
  img1: string = '../assets/image1.png';
profilePic: string | undefined;

  constructor(private router: Router) {}

  navigateToDoctorSignin() {
    this.router.navigate(['/doctor-signin']);
  }

   

  handleFileChange(event: any): void {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = () => {
        this.profilePic = reader.result as string;
      };
      reader.readAsDataURL(file);
    }
  }
}

<div class="doctorRegister-container">
  <div class="doctorRegister-container-one">
    <img [src]="img1" alt="" />
  </div>
  <div class="doctorRegister-container-two">
    <div class="signup-header">
      <div class="flex-container">
        <h4>Already have an account?</h4>
        <a (click)="navigateToDoctorSignin()">Sign in</a>
      </div>
    </div>

    <div class="header">
      <h1>Doctor Sign Up</h1>
    </div>

    <div class="textField-container">
      <div class="textField-container-one">
        <p>Full Name:</p>
        <app-textfields type="text" size="lg" placeholder="Enter your name" />
        <br />
        <p>Doctor Id:</p>
        <app-textfields
          type="text"
          size="lg"
          placeholder="Enter your id"
        /><br />
        <p>Speciality:</p>
        <app-textfields
          type="text"
          size="lg"
          placeholder="Enter speciality"
        /><br />
      </div>

      <div class="textField-container-one">
        <p>Email:</p>
        <app-textfields
          type="text"
          size="lg"
          placeholder="Enter email address"
        /><br />
        <p>Mobile Number:</p>
        <app-textfields
          type="text"
          size="lg"
          placeholder="Enter mobile number"
        /><br />
        <p>Hospital Name:</p>
        <app-textfields
          type="text"
          size="lg"
          placeholder="Enter hospital name"
        /><br />
      </div>
    </div>

    <div class="textField-container">
      <div class="textField-container-one">
        <p>Password:</p>
        <app-textfields
          type="password"
          size="lg"
          placeholder="Enter Password"
        /><br />
      </div>

      <div class="textField-container-one">
        <p>Confirm Password:</p>
        <app-textfields
          type="password"
          size="lg"
          placeholder="Re-enter Password"
        /><br />
      </div>
    </div>

    <div class="footer-container">
      <div class="profile-section">
        <ng-container *ngIf="profilePic">
          <div>
            <div class="profile-pic-container">
              <img [src]="profilePic" alt="Profile" class="profile-pic" />
            </div>
          </div>
        </ng-container>
        <div>
          <div class="label-container">
            <input
              type="file"
              id="fileInput"
              accept="image/*"
              (change)="handleFileChange($event)"
            />
            <span class="file-input-text"> Choose profile picture </span>
          </div>
        </div>
      </div>

      <div class="button-section">
        <button class="signup-button">
          <h2>Sign Up</h2>
        </button>
      </div>
    </div>
  </div>
</div>
