// vue-frontend/src/App.vue
<template>
  <div id="app">
    <!-- <TextField placeholder="Small TextField" size="small" v-model="smallTextValue" /><br/>
    <TextField placeholder="Medium TextField" size="medium" v-model="mediumTextValue" /><br/>
    <TextField placeholder="Large TextField" size="large" v-model="largeTextValue" /> -->
    <!-- <PasswordInput placeholder="Enter Password" v-model="password" /> -->
    <!-- <SelectTextField :options="options" v-model="selectedOption" placeholder="Select an option" /> -->
    <DoctorRegister />
  </div>
</template>

<script>
import TextField from "./components/TextFields.vue";
import PasswordInput from "./components/PasswordTextField.vue";
import SelectTextField from "./components/SelectTextField.vue";
import DoctorRegister from "./Pages/DoctorRegister.vue";

export default {
  name: "App",
  components: {
    TextField,
    PasswordInput,
    SelectTextField,
    DoctorRegister,
  },
  data() {
    return {
      smallTextValue: "",
      mediumTextValue: "",
      largeTextValue: "",
      password: "",
      selectedOption: "",
      options: [
        { value: "option1", label: "Option 1" },
        { value: "option2", label: "Option 2" },
        { value: "option3", label: "Option 3" },
      ],
    };
  },
};
</script>

<style>
#app {
  font-family: Arial, sans-serif;
  text-align: center;
  margin-top: 20px;
}
</style>

// react-frontend/src/App.js
import React, { useState } from "react";
import { LargeTextField, SelectTextField } from "./Components/Textfeilds";

function App() {
  const options = [
    { value: "option1", label: "Option 1" },
    { value: "option2", label: "Option 2" },
    // Add more options as needed
  ];

  const [selectedOption, setSelectedOption] = useState("");

  const handleSelectChange = (e) => {
    setSelectedOption(e.target.value);
  };

  return (
    <div className="App">
      <h1> Welcome to the eMedical App</h1>
      <LargeTextField placeholder="Enter your name" />
      <SelectTextField
        options={options}
        value={selectedOption}
        onChange={handleSelectChange}
        placeholder="Select your choice"
      />
    </div>
  );
}

export default App;
