// react-frontend/src/Pages/DoctorSignin.js
import { Link } from "react-router-dom";
import img2 from "../assets/image2.png";
import logo from "../assets/logo.png";
import { LargeTextField, PasswordInput } from "../Components/Textfeilds";
import "./DoctorSignin.css";

function DoctorSignin() {
  return (
    <div className="signin-container">
      <div className="signin-container-one">
        {/* <img style={{ width: "500px", height: "500px" }} src={logo} alt="" /> */}
        <div className="welcome-meassage">
          <h1>Hi,</h1>
          <h1>Welcome Back</h1>
        </div>

        <img src={img2} alt="" />
      </div>

      <div className="signin-container-two">
        <div className="signin-header-link">
          <h3 className="create-account-heading">Create an account?</h3>
          <Link className="create-account-heading" to="/doctor-register">
            Sign up
          </Link>
        </div>

        <div className="signin-body">
          <div className="signin-header">
            <h1>Login {""} </h1> <h1>to eHealthHub</h1>
          </div>

          <div className="signin-textfield-container">
            <LargeTextField placeholder={"Enter your Email"} />
            <PasswordInput placeholder={"Enter your password"} />
            <Link to="#" style={{ color: "white" }}>
              Forgot Password?
            </Link>
          </div>
          <div className="Signin-button-section">
            <button className="signin-button">
              <h2>Sign in</h2>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default DoctorSignin;

// angular-frontend/src/app/pages/doctor-signin/doctor-signin.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { TextfieldsComponent } from '../../../components/textfields/textfields.component';

@Component({
  selector: 'app-doctor-signin',
  standalone: true,
  imports: [TextfieldsComponent],
  templateUrl: './doctor-signin.component.html',
  styleUrl: './doctor-signin.component.css'
})
export class DoctorSigninComponent {
img2: string = '../assets/image2.png';

 constructor(private router: Router) {}

  navigateToDoctorSignup() {
    this.router.navigate(['/']);
  }

  navigateToForgotPassword(){
    this.router.navigate([]);
  }

  handleClick(): void {
    this.router.navigateByUrl('doctor-register');
  }
}

<div class="signin-container">
  <div class="signin-container-one">
    <div class="welcome-meassage">
      <h1>Hi,</h1>
      <h1>Welcome Back</h1>
    </div>
    <img [src]="img2" alt="" />
  </div>

  <div class="signin-container-two">
    <div class="signup-header">
      <div class="flex-container">
        <h3>Create an account?</h3>
        <a (click)="navigateToDoctorSignup()">Sign up</a>
      </div>
    </div>

    <div class="signin-body">
      <div class="signin-header">
        <h1>Login to eHealthHub</h1>
      </div>

      <div class="signin-textfield-container">
        <app-textfields type="text" size="lg" placeholder="Enter your email" />
        <br />
        <app-textfields
          type="password"
          size="lg"
          placeholder="Enter Password"
        /><br />
        <a (click)="navigateToForgotPassword()"> Forgot Password? </a>
      </div>

      <div class="Signin-button-section">
        <button class="signin-button" (click)="handleClick()">
          <h3>Sign in</h3>
        </button>
      </div>
    </div>
  </div>
</div>
