// react-frontend/src/Pages/PatientRegister.js
import React from "react";
import "./PatientRegister.css";
import { LargeTextField, SelectTextField } from "../Components/Textfeilds";
import { useState } from "react";

function PatientRegister() {
  const diseaseOptions = [
    { value: "1", label: "Option 1" },
    { value: "2", label: "Option 2" },
    { value: "3", label: "Option 3" },
  ];

  // State to manage the selected value
  const [selectedDisease, setSelectedDisease] = useState("");

  // Handler for the onChange event
  const handleDiseaseChange = (e) => {
    setSelectedDisease(e.target.value);
  };
  return (
    <div className="register-patient">
      <h1>Register Patient</h1>

      <div className="patient-container">
        <div className="patient-container-one">
          <p>Full Name:</p>
          <LargeTextField placeholder={"Enter your name"} />
          <br />
          <p>Age:</p>
          <LargeTextField placeholder={"Enter age"} /> <br />
          <p>Email:</p>
          <LargeTextField placeholder={"Enter email address"} /> <br />
          <p>Current Diseases</p>
          <SelectTextField
            options={diseaseOptions}
            value={selectedDisease}
            onChange={handleDiseaseChange}
            placeholder="Select disease"
          />
          <br />
          <p>Current Medication</p>
          <SelectTextField
            options={diseaseOptions}
            value={selectedDisease}
            onChange={handleDiseaseChange}
            placeholder="Select medication"
          />
          <br />
          <p>Current Treatments</p>
          <SelectTextField
            options={diseaseOptions}
            value={selectedDisease}
            onChange={handleDiseaseChange}
            placeholder="Select treatments"
          />
        </div>

        <div className="patient-container-one">
          <p>Gender:</p>
          <LargeTextField placeholder={"Gender"} /> <br />
          <p>Mobile Number:</p>
          <LargeTextField placeholder={"Enter mobile number"} /> <br />
          <p>Address:</p>
          <LargeTextField placeholder={"Enter address"} /> <br />
          <p>Register Date:</p>
          <LargeTextField placeholder={"Enter register date"} /> <br />
          <p>Past Diseases</p>
          <SelectTextField
            options={diseaseOptions}
            value={selectedDisease}
            onChange={handleDiseaseChange}
            placeholder="Select disease"
          />
          <br />
          <p>Next Appointment Date:</p>
          <LargeTextField placeholder={"Date"} />
        </div>
      </div>
      <div className="button-section">
        <button className="register-button">
          <h2>Register</h2>
        </button>
      </div>
    </div>
  );
}

export default PatientRegister;

// angular-frontend/src/app/pages/patient-register/patient-register.component.ts
import { Component } from '@angular/core';
import { SelectTextfieldComponent } from '../../../components/select-textfield/select-textfield.component';
import { TextfieldsComponent } from '../../../components/textfields/textfields.component';

@Component({
  selector: 'app-patient-register',
  standalone: true,
  imports: [TextfieldsComponent,SelectTextfieldComponent],
  templateUrl: './patient-register.component.html',
  styleUrl: './patient-register.component.css'
})
export class PatientRegisterComponent {
selectedOption: any = undefined;
  selectOptions: { value: any, label: string }[];

  constructor() {
    // Sample options data
    this.selectOptions = [
      { value: 'option1', label: 'Option 1' },
      { value: 'option2', label: 'Option 2' },
      { value: 'option3', label: 'Option 3' }
    ];
  }
}

<div class="register-patient">
  <h1>Register Patient</h1>

  <div class="patient-container">
    <div class="patient-container-one">
      <p>Full Name:</p>
      <app-textfields type="text" size="lg" placeholder="Enter your name" />
      <br />
      <p>Age:</p>
      <app-textfields type="text" size="lg" placeholder="Enter your age" />
      <br />
      <p>Email:</p>
      <app-textfields type="text" size="lg" placeholder="Enter email address" />
      <br />
      <p>Current Diseases:</p>
      <app-select-textfield
        [value]="selectedOption"
        [placeholder]="'Select disease'"
        [options]="selectOptions"
      /><br />
      <p>Current Medication:</p>
      <app-select-textfield
        [value]="selectedOption"
        [placeholder]="'Select mediaction'"
        [options]="selectOptions"
      /><br />
      <p>Current Treatments:</p>
      <app-select-textfield
        [value]="selectedOption"
        [placeholder]="'Select treatments'"
        [options]="selectOptions"
      /><br />
    </div>

    <div class="patient-container-one">
      <p>Gender:</p>
      <app-textfields type="text" size="lg" placeholder="Gender" />
      <br />
      <p>Mobile Number:</p>
      <app-textfields type="text" size="lg" placeholder="Enter mobile number" />
      <br />
      <p>Address:</p>
      <app-textfields type="text" size="lg" placeholder="Enter address" />
      <br />
      <p>Register Date:</p>
      <app-textfields type="text" size="lg" placeholder="Enter register date" />
      <br />
      <p>Past Diseases:</p>
      <br />
      <app-select-textfield
        [value]="selectedOption"
        [placeholder]="'Select disease'"
        [options]="selectOptions"
      /><br />
      <p>Next Appointment Date:</p>
      <app-textfields type="text" size="lg" placeholder="Date" />
      <br />
    </div>
  </div>

  <div class="button-section">
    <button class="register-button">
      <h2>Register</h2>
    </button>
  </div>
</div>
